version: '3'
services:

  postgres:
    image: postgres:12.3
    container_name: watch-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres