### Create watch JSON request

POST {{host}}/watches/
Content-Type: application/json

{
  "title": "watch json title",
  "price": 10,
  "description": "JSON description",
  "fountain": "R0lGODlhAQABAIAAAAUEBAAAACwAAAAAAQABAAACAkQBADs="
}

### Create watch XML request

POST {{host}}/watches/
Content-Type: application/xml

<WatchDto>
    <title>watch xml title</title>
    <price>8</price>
    <description>XML description</description>
    <fountain>R0lGODlhAQABAIAAAAUEBAAAACwAAAAAAQABAAACAkQBADs=</fountain>
</WatchDto>
### GET watch

GET {{host}}/watches/5
Accept: application/json

### GET all watches

GET {{host}}/watches/
Accept: application/json

###
